language: rust
cache: cargo
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
sudo: true
before_install:
  - sudo apt-get update
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
before_script:
  - source $HOME/.cargo/env
  - |
      [[ "$TRAVIS_RUST_VERSION" == "stable" ]] && rustup component add clippy && export CLIPPY=true
  - |
      [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]] && export PUBLISH_DOCS=true
  - |
      [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]] && export COVERAGE=true
script:
  - cargo test
  - .ci/build/linting.sh
after_success:
  - .ci/post-build/publish-docs.sh
  - .ci/post-build/coverage.sh