language: rust
cache: cargo
sudo: true

DEPLOY_TO_GITHUB: &DEPLOY_TO_GITHUB
  before_deploy:
    - name="stegano-$TRAVIS_TAG-$TARGET"
    - mkdir $name
    - cp target/$TARGET/release/stegano $name/
    - cp README.md LICENSE-MIT LICENSE-APACHE $name/
    - tar czvf $name.tar.gz $name
  deploy:
    provider: releases
    api_key: $GH_TOKEN
    file: stegano-$TRAVIS_TAG-$TARGET.tar.gz
    skip_cleanup: true
    on:
      branch: master
      tags: true

matrix:
  include:

  # tests pass
  - rust: stable
    before_install:
      - sudo apt-get update
    addons:
      apt:
        packages:
          - libcurl4-openssl-dev
          - libelf-dev
          - libdw-dev
          - cmake
          - gcc
          - binutils-dev
          - libssl-dev
    before_cache: cargo install cargo-tarpaulin -f
    script:
      - cargo clean
      - cargo test --all --locked
      - rustup component add clippy
      - cargo clippy --all-targets -- -D warnings
      - rustup component add rustfmt-preview
      - cargo fmt --all -- --check
    after_success: |
      cargo tarpaulin --out Xml
      bash <(curl -s https://codecov.io/bash)
    env: RUST_BACKTRACE=1

  # dist linux binary
  - env: JOB=dist-linux TARGET=x86_64-unknown-linux-musl
    rust: stable
    before_script: rustup target add $TARGET
    script: cargo build --release --target $TARGET --locked
    addons:
      apt:
        packages:
          - musl-tools
    <<: *DEPLOY_TO_GITHUB

  # dist OSX binary
  - env: JOB=dist-osx MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
    os: osx
    rust: stable
    script: cargo build --release --target $TARGET --locked
    <<: *DEPLOY_TO_GITHUB

notifications:
  email:
    on_success: never
