language: rust
cache: cargo
os:
  - linux
#  - osx
rust:
  - stable
#  - beta
#  - nightly
sudo: true
before_install:
  - sudo apt-get update
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
before_script:
  - source $HOME/.cargo/env
  - |
      export CLIPPY=$([[ "$TRAVIS_RUST_VERSION" == "stable" ]])
  - |
      if [[ $CLIPPY ]]; then rustup component add clippy; fi
  - |
      export PUBLISH_DOCS=$([[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]])
  - |
      export COVERAGE=$([[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]])
script:
  - cargo build
  - cargo test
  - .ci/build/linting.sh
after_success:
  - .ci/post-build/publish-docs.sh
  - .ci/post-build/coverage.sh