[package]
name = "stegano"
version = "0.0.1"
authors = ["Sven Assmann <sven.assmann.it@gmail.com>"]
edition = "2018"

[workspace]

[dependencies]
image = "0.22.3"
clap = "2.33.0"
bitstream-io = "0.8"
block-modes = "0.3.3"
aes-soft = "0.3.3"
hex-literal = "0.2.1"
futures-preview = "=0.3.0-alpha.19"
zip = "0.5.3"
byteorder = "1.3.2"

[dev-dependencies]
speculate = "0.1"
criterion = "0.3.0"

[[bench]]
name = "byte_reader_benchmark"
harness = false