[package]
name = "stegano-core"
description = "Steganography core library for stegano-cli. Supports hiding data in PNG images via LSB Encoding."
version = "0.3.1-beta.1"
authors = ["Sven Assmann <sven.assmann.it@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
homepage = "https://www.stegano.org"
readme = "README.md"
keywords = ["steganography", "image", "png", "hiding", "unveil"]
categories = ["Encoding", "Image processing", "Images"]
maintenance = { status = "actively-developed" }
repository = "https://github.com/steganogram/core.stegano.org"
exclude = ["resources/*", "tests/*", ".gitignore", ".travis.yml"]

[badges]
travis-ci = { repository = "steganogram/core.stegano.org", branch = "master" }
codecov = { repository = "steganogram/core.stegano.org", branch = "master", service = "github" }

[workspace]

[dependencies]
image = "0.22.3"
bitstream-io = "0.8"
block-modes = "0.3.3"
aes-soft = "0.3.3"
hex-literal = "0.2.1"
futures-preview = "=0.3.0-alpha.19"
zip = "0.5.4"
bzip2 = "0.3.3"
deflate = "0.8.2"
byteorder = "1.3.2"

[dev-dependencies]
speculate = "0.1"
criterion = "0.3.0"
tempdir = "0.3.7"

[[bench]]
name = "byte_reader_benchmark"
harness = false