[package]
name = "stegano"
version = "0.0.1"
authors = ["Sven Assmann <sven.assmann.it@gmail.com>"]
edition = "2018"

[workspace]

[dependencies]
image = "0.22.3"
clap = "2.33.0"
bitstream-io = "0.8"
futures-preview = "=0.3.0-alpha.19"

[dev-dependencies]
speculate = "0.1"