name: stegano
base: core18
adopt-info: stegano
summary: Image and Audio Steganography
description: |
  A cross-platform command line tool for steganography, focused on performance and simplicity.

grade: stable
confinement: strict

parts:
  stegano:
    plugin: rust
    source: .
    source-subdir: stegano-cli
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags)"

apps:
  stegano:
    command: bin/stegano
    plugs:
      - home
