# inspired by https://github.com/extrawurst/gitui/blob/master/.github/workflows/cd.yml
name: CD

on:
  push:
    tags:
      - '*'

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Setup MUSL on Linux
        if: matrix.os == 'ubuntu-latest'
        run:
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get -qq install musl-tools

      - run: echo ::set-output name=target::"x86_64-unknown-linux-musl"
        if: matrix.os == 'ubuntu-latest'
        id: target
      - run: echo ::set-output name=target::"x86_64-apple-darwin"
        if: matrix.os == 'macos-latest'
        id: target
      - run: echo ::set-output name=target::"x86_64-pc-windows-gnu"
        if: matrix.os == 'windows-latest'
        id: target

      - name: Building
        run: cargo build --release --target ${{ steps.target.outputs.target }} --locked
      - name: Packaging
        run: |
          TARGET=${{ steps.target.outputs.target }}
          strip target/$TARGET/release/stegano
          name="stegano-${{ steps.get_version.outputs.version }}-$TARGET"
          mkdir $name
          cp target/$TARGET/release/stegano $name/
          cp README.md LICENSE $name/
          tar czvf $name.tar.gz $name
          mkdir releases
          cp $name.tar.gz releases/