## references:
# cache: https://github.com/actions/cache/blob/main/examples.md#rust---cargo
# audit: https://github.com/actions-rs/audit-check
# "needs": https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds

name: Release-Test
on:
  push:
    branches: ['*']

# NOTE: needs to stay in sync with ./build.yml
jobs:
  release:
    name: post / github release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup | rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
      - run: cargo install cargo-deb
      - uses: Swatinem/rust-cache@v1
      - name: Get version from tag
        id: tag_name
        run: echo ::set-output name=current_version::$(git describe --tags --abbrev=0)
        shell: bash
      - name: Get Changelog Entry
        id: changelog_reader
        # https://github.com/marketplace/actions/changelog-reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md
      - run: cargo deb -p stegano-cli
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the "Get Changelog Entry" step above, referencing it's ID to get its outputs object.
          # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.changelog_reader.outputs.version }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          draft: ${{ steps.changelog_reader.outputs.status == 'unreleased' }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/debian/stegano-cli_${{ steps.tag_name.outputs.current_version }}_amd64.deb
          asset_name: stegano_${{ steps.tag_name.outputs.current_version }}_amd64.deb
          asset_content_type: application/vnd.debian.binary-package